import type { PartsMeshLayerId, PartsRigDef } from './parts';
import type { MeshGridSpec } from './types';

/**
 * Reference def for the parts-over-closed-core evaluator (`parts.ts`). The
 * trex-pf-r0 probe pack this def described was ARCHIVED with the parts-first
 * probe (see docs/rebuild/IR-LESSONS.md) — the def stays as the evaluator's
 * test fixture and as the geometry starting point for the socket-era rigs,
 * which reuse the proven closed-core z-contract. Nothing in apps/web loads it.
 */

const PARTS_MESH_SPECS: Record<PartsMeshLayerId, MeshGridSpec> = {
  core: { columns: 8, rows: 5 },
  neck: { columns: 4, rows: 4 },
  tail: { columns: 8, rows: 3 },
};

export const TREX_PF_RIG_DEF: PartsRigDef = {
  rigKind: 'theropod-parts',
  speciesId: 'trex-pf',
  label: 'Tyrannosaurus rex (parts-first)',
  packPath: 'rigs/trex-pf-r0',
  masterFile: 'trex-pf-master.png',
  seed: 20260722,
  // Whole-piece legs pivot at the hip with no knee to counter-rotate, so the
  // seam-clean stride envelope is tighter than the twelve-layer cut's ±1.
  strideRange: { min: -0.6, max: 0.6 },
  // Mouth is painted OPEN on the head (dark interior) with a separate jaw, so
  // neutral is the widest gape; the jaw can only clench shut from there.
  jawRange: { min: -8, max: 0 },
  pivots: {
    core: { x: 748, y: 408 },
    tail: { x: 1030, y: 440 },
    neck: { x: 475, y: 410 },
    head: { x: 250, y: 320 },
    jaw: { x: 250, y: 365 },
    farHip: { x: 610, y: 540 },
    nearHip: { x: 825, y: 542 },
    farShoulder: { x: 413, y: 483 },
    nearShoulder: { x: 450, y: 480 },
  },
  // Bounds as generated by the archived pack's manifest; the mesh rest grid
  // and pattern UVs in the pose tests are built from them.
  layerBounds: {
    'far-leg': { x: 494, y: 520, width: 223, height: 270 },
    tail: { x: 983, y: 378, width: 486, height: 124 },
    core: { x: 430, y: 270, width: 636, height: 276 },
    'far-arm': { x: 383, y: 475, width: 64, height: 113 },
    'near-leg': { x: 737, y: 522, width: 196, height: 272 },
    'near-arm': { x: 413, y: 471, width: 70, height: 108 },
    neck: { x: 228, y: 296, width: 299, height: 196 },
    'jaw-lower': { x: 76, y: 342, width: 172, height: 92 },
    'head-upper': { x: 37, y: 217, width: 304, height: 193 },
  },
  meshSpecs: PARTS_MESH_SPECS,
  deform: {
    core: {
      liftAmp: 8,
      dorsalRamp: [530, 285],
      frontFade: [432, 580],
      rearFade: [940, 1066],
      chest: { amp: 2.2, cx: 700, halfW: 320, yRamp: [300, 520] },
      sample: { x: 460, y: 500 },
      settleAmp: 1,
    },
    neck: { xBase: 510, xHead: 260, liftBase: 5, liftHead: 4.5, rotPerHeadDeg: 0.45, rotPerBreath: -0.9 },
    head: { dxPerDeg: -0.5, dyPerDegUp: -0.12, dyPerDegDown: -0.3 },
    arms: { breathRot: -1.0 },
    legs: { nearAmp: 5, farAmp: -4, nearLift: -3 },
    tail: { ramp: [1066, 1440], swayRot: 6, strideRot: 2.6, breathRot: -0.7, shiftX: -4, shiftY: 2 },
  },
};

export const PARTS_RIG_DEFS: Record<string, PartsRigDef> = {
  'trex-pf': TREX_PF_RIG_DEF,
};
