import type { SpeciesDef } from './types';

/**
 * The M0 roster: the three archetype exemplars validated in the Morph Lab
 * prototype (docs/rebuild/prototype/morphlab.html). Morph vectors are the
 * prototype's tuned values, verbatim — they are known-good geometry.
 *
 * Facts are salvaged from legacy/src/data/dinosaurDatabase.ts (the single
 * source of paleontology truth). M1 expands this file wave by wave.
 */
export const SPECIES = {
  tyrannosaurus: {
    id: 'tyrannosaurus',
    name: 'Tyrannosaurus Rex',
    archetype: 'theropod',
    inV1: true,
    facts: {
      scientificName: 'Tyrannosaurus rex',
      period: 'Late Cretaceous',
      era: 'Mesozoic',
      diet: 'Carnivore',
      habitat: 'Forests and plains',
      description: 'The king of dinosaurs, most famous apex predator of all time',
      lengthMeters: 12.3,
      weightKg: 8400,
      discoveryLocation: 'Montana, USA',
    },
    morph: {
      hipY: 285,
      shoulderRise: 20,
      bodyLen: 145,
      archUp: 15,
      neckLen: 75,
      neckUp: 55,
      snoutLen: 60,
      headSize: 52,
      snoutTip: 18,
      neckThick: 36,
      tailLen: 265,
      tailDrop: 50,
      tailThick: 48,
      bodyThick: 96,
      chestThick: 72,
      fLegLen: 60,
      fLegThick: 11,
      hLegThick: 42,
    },
    features: [{ kind: 'teeth', slot: 'head' }],
    syllables: { prefix: 'Tyranno', duo: 'rex', mid: 'rexo', suffix: 'rex' },
    stats: { attack: 92, defense: 28, speed: 74, brains: 58 },
    uiColor: '#b5482a',
  },

  triceratops: {
    id: 'triceratops',
    name: 'Triceratops',
    archetype: 'ceratopsian',
    inV1: true,
    facts: {
      scientificName: 'Triceratops horridus',
      period: 'Late Cretaceous',
      era: 'Mesozoic',
      diet: 'Herbivore',
      habitat: 'Plains and woodlands',
      description: 'Three-horned herbivore that could defend itself against T-Rex',
      lengthMeters: 9,
      weightKg: 12000,
      discoveryLocation: 'North America',
    },
    morph: {
      hipY: 320,
      shoulderRise: -8,
      bodyLen: 140,
      archUp: 6,
      neckLen: 50,
      neckUp: 6,
      snoutLen: 48,
      headSize: 44,
      snoutTip: 8,
      neckThick: 46,
      tailLen: 190,
      tailDrop: 78,
      tailThick: 40,
      bodyThick: 100,
      chestThick: 86,
      fLegLen: 150,
      fLegThick: 26,
      hLegThick: 36,
    },
    features: [
      { kind: 'browHorns', slot: 'head' },
      { kind: 'noseHorn', slot: 'head' },
      { kind: 'frill', slot: 'head' },
    ],
    syllables: { prefix: 'Tricera', duo: 'ceratops', mid: 'cerato', suffix: 'tops' },
    stats: { attack: 34, defense: 88, speed: 38, brains: 42 },
    uiColor: '#4f5fb0',
  },

  stegosaurus: {
    id: 'stegosaurus',
    name: 'Stegosaurus',
    archetype: 'armored',
    inV1: true,
    facts: {
      scientificName: 'Stegosaurus stenops',
      period: 'Late Jurassic',
      era: 'Mesozoic',
      diet: 'Herbivore',
      habitat: 'Fern prairies',
      description: 'Iconic plated dinosaur with defensive tail spikes',
      lengthMeters: 9,
      weightKg: 5000,
      discoveryLocation: 'Colorado, USA',
    },
    morph: {
      hipY: 310,
      shoulderRise: -30,
      bodyLen: 140,
      archUp: 42,
      neckLen: 60,
      neckUp: -18,
      snoutLen: 32,
      headSize: 26,
      snoutTip: 7,
      neckThick: 26,
      tailLen: 235,
      tailDrop: 105,
      tailThick: 40,
      bodyThick: 104,
      chestThick: 70,
      fLegLen: 132,
      fLegThick: 21,
      hLegThick: 34,
    },
    features: [
      { kind: 'plates', slot: 'back' },
      { kind: 'tailSpikes', slot: 'tail' },
    ],
    syllables: { prefix: 'Stego', duo: 'stega', mid: 'stego', suffix: 'saurus' },
    stats: { attack: 26, defense: 84, speed: 20, brains: 14 },
    uiColor: '#1f7d6d',
  },

  // --- M1 Wave 2: archetype exemplars (sauropod + ornithopod) ------------------
  brachiosaurus: {
    id: 'brachiosaurus',
    name: 'Brachiosaurus',
    archetype: 'sauropod',
    inV1: true,
    facts: {
      scientificName: 'Brachiosaurus altithorax',
      period: 'Late Jurassic',
      era: 'Mesozoic',
      diet: 'Herbivore',
      habitat: 'Woodlands',
      description: 'Towering high-browser that could reach treetops',
      lengthMeters: 23,
      weightKg: 28000,
      discoveryLocation: 'Colorado, USA',
    },
    // Sauropod: long neck rising high off high shoulders, small head, long
    // front legs (front > hind — the "altithorax" build), body sloping down to
    // a long tail. Stress-tests the neck/tail/size ranges (ROADMAP M1).
    morph: {
      hipY: 300,
      shoulderRise: 72,
      bodyLen: 168,
      archUp: 8,
      neckLen: 208,
      neckUp: 168,
      snoutLen: 34,
      headSize: 30,
      snoutTip: 11,
      neckThick: 36,
      tailLen: 268,
      tailDrop: 26,
      tailThick: 44,
      bodyThick: 122,
      chestThick: 104,
      fLegLen: 224,
      fLegThick: 32,
      hLegThick: 44,
    },
    features: [],
    syllables: { prefix: 'Brachio', duo: 'brachion', mid: 'brachio', suffix: 'saurus' },
    stats: { attack: 30, defense: 78, speed: 22, brains: 30 },
    uiColor: '#6f8a6a',
  },

  parasaurolophus: {
    id: 'parasaurolophus',
    name: 'Parasaurolophus',
    archetype: 'ornithopod',
    inV1: true,
    facts: {
      scientificName: 'Parasaurolophus walkeri',
      period: 'Late Cretaceous',
      era: 'Mesozoic',
      diet: 'Herbivore',
      habitat: 'Coastal plains',
      description: 'Musical hadrosaur that could produce trumpeting calls',
      lengthMeters: 9.5,
      weightKg: 2500,
      discoveryLocation: 'Alberta, Canada',
    },
    // Ornithopod: biped-leaning hadrosaur with a broad duck-bill (wide snout
    // tip), deep counterbalancing tail, and short raised forelimbs. Carries the
    // tube crest feature.
    morph: {
      hipY: 300,
      shoulderRise: 22,
      bodyLen: 150,
      archUp: 10,
      neckLen: 72,
      neckUp: 44,
      snoutLen: 54,
      headSize: 40,
      snoutTip: 21,
      neckThick: 34,
      tailLen: 236,
      tailDrop: 52,
      tailThick: 52,
      bodyThick: 100,
      chestThick: 80,
      fLegLen: 122,
      fLegThick: 18,
      hLegThick: 46,
    },
    features: [{ kind: 'crest', slot: 'head' }],
    syllables: { prefix: 'Para', duo: 'lophus', mid: 'louro', suffix: 'lophus' },
    stats: { attack: 24, defense: 52, speed: 60, brains: 48 },
    uiColor: '#c08a4a',
  },

  // --- M1 Wave 3: armored, sail, feathered, and dome-skulled roster ------------
  ankylosaurus: {
    id: 'ankylosaurus',
    name: 'Ankylosaurus',
    archetype: 'armored',
    inV1: true,
    facts: {
      scientificName: 'Ankylosaurus magniventris',
      period: 'Late Cretaceous',
      era: 'Mesozoic',
      diet: 'Herbivore',
      habitat: 'Forests and plains',
      description: 'Living tank with heavy armor and devastating tail club',
      lengthMeters: 6.25,
      weightKg: 6000,
      discoveryLocation: 'Montana, USA',
    },
    // Low, wide, heavy quadruped: hip near the ground, short thick columnar
    // legs, broad low-slung head, rounded armored back, club-tipped tail.
    morph: {
      hipY: 350,
      shoulderRise: -6,
      bodyLen: 150,
      archUp: 20,
      neckLen: 42,
      neckUp: -12,
      snoutLen: 40,
      headSize: 40,
      snoutTip: 16,
      neckThick: 48,
      tailLen: 200,
      tailDrop: 24,
      tailThick: 44,
      bodyThick: 128,
      chestThick: 100,
      fLegLen: 100,
      fLegThick: 30,
      hLegThick: 46,
    },
    features: [{ kind: 'tailClub', slot: 'tail' }],
    syllables: { prefix: 'Anky', duo: 'ankylus', mid: 'ankylo', suffix: 'saurus' },
    stats: { attack: 40, defense: 92, speed: 18, brains: 20 },
    uiColor: '#7a7266',
  },

  spinosaurus: {
    id: 'spinosaurus',
    name: 'Spinosaurus',
    archetype: 'theropod',
    inV1: true,
    facts: {
      scientificName: 'Spinosaurus aegyptiacus',
      period: 'Early Cretaceous',
      era: 'Mesozoic',
      diet: 'Piscivore',
      habitat: 'Rivers and swamps',
      description: 'Largest known carnivorous dinosaur, adapted for aquatic life',
      lengthMeters: 15,
      weightKg: 7400,
      discoveryLocation: 'Egypt',
    },
    // Large biped with a long narrow crocodilian snout, deep paddle tail, and
    // the signature dorsal sail (a back feature).
    morph: {
      hipY: 292,
      shoulderRise: 12,
      bodyLen: 152,
      archUp: 12,
      neckLen: 78,
      neckUp: 38,
      snoutLen: 80,
      headSize: 46,
      snoutTip: 12,
      neckThick: 36,
      tailLen: 280,
      tailDrop: 58,
      tailThick: 54,
      bodyThick: 100,
      chestThick: 78,
      fLegLen: 74,
      fLegThick: 13,
      hLegThick: 42,
    },
    features: [
      { kind: 'sail', slot: 'back' },
      { kind: 'teeth', slot: 'head' },
    ],
    syllables: { prefix: 'Spino', duo: 'spinus', mid: 'spino', suffix: 'saurus' },
    stats: { attack: 88, defense: 44, speed: 58, brains: 50 },
    uiColor: '#3f7a8a',
  },

  velociraptor: {
    id: 'velociraptor',
    name: 'Velociraptor',
    archetype: 'theropod',
    inV1: true,
    facts: {
      scientificName: 'Velociraptor mongoliensis',
      period: 'Late Cretaceous',
      era: 'Mesozoic',
      diet: 'Carnivore',
      habitat: 'Desert plains',
      description: 'Intelligent pack hunter with deadly sickle claws',
      lengthMeters: 2,
      weightKg: 15,
      discoveryLocation: 'Mongolia',
    },
    // Small, light, agile biped: compact body, slender neck and legs, a long
    // stiff near-horizontal tail for balance, and a feathered integument.
    morph: {
      hipY: 300,
      shoulderRise: 16,
      bodyLen: 120,
      archUp: 10,
      neckLen: 70,
      neckUp: 52,
      snoutLen: 52,
      headSize: 34,
      snoutTip: 10,
      neckThick: 26,
      tailLen: 250,
      tailDrop: 18,
      tailThick: 30,
      bodyThick: 72,
      chestThick: 56,
      fLegLen: 70,
      fLegThick: 10,
      hLegThick: 32,
    },
    features: [
      { kind: 'feathers', slot: 'skin' },
      { kind: 'teeth', slot: 'head' },
    ],
    syllables: { prefix: 'Veloci', duo: 'raptor', mid: 'velo', suffix: 'raptor' },
    stats: { attack: 66, defense: 30, speed: 88, brains: 74 },
    uiColor: '#a5763f',
  },

  // Dracorex is the pachycephalosaurid present in the salvaged database; it
  // carries the domeSkull feature and fills the head-butter slot in Wave 1.
  // (Pachycephalosaurus itself is not in dinosaurDatabase.ts, and facts are
  // never invented — CLAUDE.md.)
  dracorex: {
    id: 'dracorex',
    name: 'Dracorex',
    archetype: 'ornithopod',
    inV1: true,
    facts: {
      scientificName: 'Dracorex hogwartsia',
      period: 'Late Cretaceous',
      era: 'Mesozoic',
      diet: 'Herbivore',
      habitat: 'Forests',
      description: "The 'Dragon King of Hogwarts' with an elaborate spiky skull",
      lengthMeters: 4,
      weightKg: 45,
      discoveryLocation: 'South Dakota, USA',
    },
    // Small ornithischian biped with an ornamented, thickened skull.
    morph: {
      hipY: 310,
      shoulderRise: 18,
      bodyLen: 128,
      archUp: 12,
      neckLen: 58,
      neckUp: 40,
      snoutLen: 44,
      headSize: 38,
      snoutTip: 14,
      neckThick: 30,
      tailLen: 210,
      tailDrop: 40,
      tailThick: 38,
      bodyThick: 84,
      chestThick: 64,
      fLegLen: 96,
      fLegThick: 13,
      hLegThick: 38,
    },
    features: [{ kind: 'domeSkull', slot: 'head' }],
    syllables: { prefix: 'Draco', duo: 'dracus', mid: 'draco', suffix: 'rex' },
    stats: { attack: 30, defense: 58, speed: 54, brains: 34 },
    uiColor: '#96704a',
  },
} as const satisfies Record<string, SpeciesDef>;

export type SpeciesId = keyof typeof SPECIES;

export const SPECIES_IDS = Object.keys(SPECIES) as SpeciesId[];

export function getSpecies(id: SpeciesId): SpeciesDef {
  return SPECIES[id];
}

export function isSpeciesId(id: string): id is SpeciesId {
  // Object.hasOwn, not `in`: untrusted ids like "constructor" must not
  // validate via the prototype chain (this is the share-URL trust boundary).
  return Object.hasOwn(SPECIES, id);
}
